AGENT_REGISTRY_URL = "https://geminicli.com/extensions/"

STRATEGY_TACTICS = """
You are an expert in Spec-Driven Development (SDD). 
You understand the relationship between Strategy and Tactics:
- **Strategy (Obsidian)**: Defines the "What" and "Why". It holds the project's soul, long-term roadmap, and domain-specific principles.
- **Tactics (spec-kit)**: Defines the "How". It executes iterative SDD cycles (Specify -> Plan -> Implement) to generate concrete code and assets.

Always check the Obsidian strategy before proposing tactical tasks.
"""

MANGA_GUIDE = """
You are a master manga creator. When storyboarding in SDD:
1. **Frame Division**: Plan panels to guide the reader's eye. Use varying panel sizes for dramatic effect.
2. **Character Settings**: Define both visual attributes (SVG templates) and personality traits.
3. **Dialogue and Action**: Use clear "Given/When/Then" scenarios for scene transitions.
4. **Multilingual Support**: Plan for text substitution in SVG layers (e.g., ja/, en/).
"""

VIDEO_GUIDE = """
You are a professional video director. When storyboarding in SDD:
1. **Camera Work**: Specify shots (Close-up, Wide shot) and movement (Pan, Zoom, Tilt).
2. **Timing**: Define the duration of each cut in seconds.
3. **Audio**: Include SE (Sound Effects) and BGM (Background Music) cues in the specification.
4. **Implementation**: Use placeholders or generate scene descriptions for AI video generators.
"""

CAD_GUIDE = """
You are a CAD engineer specializing in JSCAD. When storyboarding in SDD:
1. **Parametric Modeling**: Design components with adjustable parameters.
2. **Primitives**: Use geometric primitives (cube, sphere, cylinder) as building blocks.
3. **Component Logic**: Build complex models by combining and subtracting simple shapes.
4. **JSCAD-Tool**: Follow the gemini-jscad pattern: write .js code, then convert to .stl.
"""

# Phase 3: Bootstrap Rules
BOOTSTRAP_RULES = """
### VI. Feature Branch Lifecycle & Merging
Upon completion of a feature (verified by tests and SDD checklist), the user must be prompted to merge the work branch (e.g., `001-...`) into `main`. **Completed feature branches MUST NOT be deleted.** They must be preserved to maintain a historical record of the SDD process and to ensure the `spec-kit` numbering logic (which scans existing branches) functions correctly.

### VII. In-Code Prompt Definition (Self-Contained Logic)
To minimize user configuration and ensure consistency, all SDD-specific instructions, storyboarding rules, and domain-specific guidance must be defined as `Prompts` within the FastMCP server code. This ensures that the AI agent's behavior and domain knowledge are bundled directly with the tool.

### VIII. Git Commit Procedure
To prevent multi-line commit messages from being misinterpreted as shell commands:
1. All commit messages MUST be written to a temporary file (e.g., `.gemini/commit_msg.txt`) before committing.
2. The `git commit` command MUST use the `-F` (or `--file`) option pointing to this temporary file.
3. Temporary commit message files MUST reside in directories ignored by Git (e.g., `.gemini/`) to avoid accidental leakage or tracking.
"""

# Phase 3: Agent Profiles
AGENT_EXTENSION_GUIDE_TEMPLATE = f"""
When installing spec-kit extensions for your AI agent, search the official registry for the latest tools:
{{AGENT_REGISTRY_URL}}

Use the following directory mapping for manual installations:

| AI Agent | Extension Command Directory |
| :--- | :--- |
| **GitHub Copilot** | `.github/prompts/` |
| **Claude Code** | `.claude/commands/` |
| **Gemini CLI** | `.gemini/commands/` |
| **Cursor** | `.cursor/commands/` |
| **Windsurf** | `.windsurf/workflows/` |
| **Codex CLI** | `.agents/skills/` |

To add a command, place the markdown definition file in the corresponding directory. 
Shared templates go to `.specify/templates/`.
"""

BUILD_ORGANIZATION_GUIDE = """
# Spec-Craft Build Organization Guide

All assets generated by the SDD pipeline are stored in the `build/` directory with the following hierarchy:

- `build/manga/<lang>/<filename>.svg`: Manga scenes and diagrams.
- `build/cad/universal/<filename>.stl`: CAD models and components.
- `build/assets/universal/`: Shared resources (images, sounds).

When proposing builds, ensure you use the correct domain and language context to maintain a clean project structure.
"""

BLENDER_GUIDE = """
You are a Blender automation expert. When storyboarding 3D scenes (Bonkei) in SDD:
1. **Low-Poly Aesthetic**: Use simple geometric primitives (cones for mountains, cylinders for trees).
2. **Tray Landscape (Bonkei)**: All elements must be contained within a base tray (width x depth).
3. **bpy Integration**: Generate scripts that use the `bpy` module for object creation, positioning, and material assignment.
4. **Modularity**: Create reusable functions for landscape features.

Always output a complete Python script that can be run with `blender --python`.
"""

BONSAI_GUIDE = """
You are an expert in BIM (Building Information Modeling) using Bonsai (BlenderBIM).
When storyboarding architectural projects in SDD:
1. **IFC Standards**: Use Industry Foundation Classes (IfcWall, IfcSlab, IfcWindow) for all building elements.
2. **Spatial Hierarchy**: Organise elements into IfcSite -> IfcBuilding -> IfcBuildingStorey.
3. **Parametric BIM**: Define geometric properties using IFC attributes rather than simple mesh scaling.
4. **Bonsai Operators**: Use `bpy.ops.bim.*` operators to manage the IFC database.

Generate Python scripts that bridge Obsidian architectural strategies with IFC-compliant scenes.
"""

TEST_PYPI_CHECKLIST = """
# Test PyPI Release Checklist

Follow these steps for a successful staging release:
1. **Version Update**: Increment `version` in `pyproject.toml`.
2. **Build Verification**: Run `uv build` and check `dist/` for wheel and sdist.
3. **Local Install Test**: `pip install dist/*.whl` in a clean venv.
4. **Upload to Test PyPI**:
   ```bash
   uv run python -m twine upload --repository testpypi dist/*
   ```
5. **Verify Installation from Test PyPI**:
   ```bash
   pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple spec-craft
   ```
"""

GENERATIVE_WORKFLOW_GUIDE = """
# Spec-Craft Generative Asset Workflow

To translate a strategic roadmap in Obsidian into creative assets (Images, Music, Video), follow these steps:

1. **Strategic Spec**: Analyze the target scene or chapter in Obsidian (use `read_storyboard`).
2. **Tactics Verification**: Check if the required generative extensions are installed (use `check_generative_capabilities`).
3. **Drafting**: Use the domain-specific guide (Manga, Video, etc.) to draft a tactical specification for the asset.
4. **Implementation**: Trigger the generation. For built-in drivers (SVG, CAD), use spec-craft tools. For external extensions (like Nano Banana), use their specific slash commands.
5. **Organization**: Ensure all final assets are placed in the hierarchical `build/` directory for consistency.
"""
